# Generated by Django 4.2.4 on 2023-09-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_in',
            name='room_type',
            field=models.CharField(choices=[('Deluxe', 'Deluxe'), ('family', 'family'), ('Somiking', 'Somiking')], default='Deluxe', max_length=100),
        ),
    ]
