# Generated by Django 4.2.4 on 2023-09-09 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_check_in_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.CharField(choices=[('1 Star', '1 Star'), ('2 Star', '2 Star'), ('3 Star', '3 Star'), ('4 Star', '4 Star'), ('5 Star', '5 Star')], default='5 Star', max_length=100)),
                ('review', models.TextField()),
                ('image', models.ImageField(default='', upload_to='images')),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
