# Generated by Django 4.2.4 on 2023-09-09 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
